language: go
sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: "1.25.4"

before_install:
  - docker pull redis
  - docker run -d -p 6379:6379 redis

script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test
