version: '2'
services:
  redis:
    image: redis
    ports:
    - 6379:6379
    volumes:
    - ./data/redis/data:/data
    - ./data/redis/conf:/data/conf
    - ./data/redis/logs:/data/logs

  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
    - 8001:8001
    volumes:
    - ./data/redis/insight:/db
